
import java.awt.Cursor;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Booking.java
 *
 * Created on 22 Oct, 2018, 10:35:37 PM
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Booking extends javax.swing.JFrame {
String adate="",amonth="",ayear="",ddate="",dmonth="",dyear="",se="";



    /** Creates new form Booking */
    public Booking() {
   
        initComponents();
    }
  public Booking(String para){
         initComponents();
         l12.setText(para);

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        arr = new javax.swing.JTextField();
        depa = new javax.swing.JTextField();
        adv = new javax.swing.JTextField();
        charg = new javax.swing.JTextField();
        m1 = new javax.swing.JRadioButton();
        f1 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        ron = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        rn = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        ag11 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        depa1 = new javax.swing.JTextField();
        adv1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        charg1 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        l12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        viewm = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        MainMenu = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        backm = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room Number");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reservation Number");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sex");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Arrival");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Departure");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Advance");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Charges");

        add.setBackground(new java.awt.Color(36, 47, 65));
        add.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setBorder(null);

        arr.setBackground(new java.awt.Color(36, 47, 65));
        arr.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        arr.setForeground(new java.awt.Color(255, 255, 255));
        arr.setBorder(null);
        arr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                arrFocusLost(evt);
            }
        });
        arr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                arrKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrKeyTyped(evt);
            }
        });

        depa.setBackground(new java.awt.Color(36, 47, 65));
        depa.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        depa.setForeground(new java.awt.Color(255, 255, 255));
        depa.setBorder(null);
        depa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                depaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depaKeyTyped(evt);
            }
        });

        adv.setBackground(new java.awt.Color(36, 47, 65));
        adv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        adv.setForeground(new java.awt.Color(255, 255, 255));
        adv.setBorder(null);
        adv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                advKeyPressed(evt);
            }
        });

        charg.setBackground(new java.awt.Color(36, 47, 65));
        charg.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        charg.setForeground(new java.awt.Color(255, 255, 255));
        charg.setBorder(null);

        m1.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(m1);
        m1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("Male");

        f1.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(f1);
        f1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        f1.setText("Female");

        name.setBackground(new java.awt.Color(36, 47, 65));
        name.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);

        ron.setBackground(new java.awt.Color(36, 47, 65));
        ron.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ron.setForeground(new java.awt.Color(255, 255, 255));
        ron.setBorder(null);

        rn.setEditable(false);
        rn.setBackground(new java.awt.Color(36, 47, 65));
        rn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        rn.setForeground(new java.awt.Color(255, 255, 255));
        rn.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Age");

        age.setBackground(new java.awt.Color(36, 47, 65));
        age.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setBorder(null);
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        ag11.setBackground(new java.awt.Color(36, 47, 65));
        ag11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ag11.setForeground(new java.awt.Color(255, 255, 255));
        ag11.setBorder(null);
        ag11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ag11KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ag11KeyTyped(evt);
            }
        });

        depa1.setBackground(new java.awt.Color(36, 47, 65));
        depa1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        depa1.setForeground(new java.awt.Color(255, 255, 255));
        depa1.setBorder(null);
        depa1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                depa1FocusLost(evt);
            }
        });
        depa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                depa1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depa1KeyTyped(evt);
            }
        });

        adv1.setBackground(new java.awt.Color(36, 47, 65));
        adv1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        adv1.setForeground(new java.awt.Color(255, 255, 255));
        adv1.setBorder(null);
        adv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adv1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adv1KeyTyped(evt);
            }
        });

        charg1.setBackground(new java.awt.Color(36, 47, 65));
        charg1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        charg1.setForeground(new java.awt.Color(255, 255, 255));
        charg1.setBorder(null);
        charg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                charg1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                charg1KeyTyped(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));

        l1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Book");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        l1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(97, 212, 195));

        l3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("New Booking");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        l3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l3MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator13)
                            .addComponent(adv1)
                            .addComponent(jSeparator4)
                            .addComponent(charg1)
                            .addComponent(jSeparator14)
                            .addComponent(depa1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator10)
                                        .addComponent(ron, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(m1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(f1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(ag11)
                                        .addComponent(jSeparator5)
                                        .addComponent(arr, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56))
                                        .addComponent(jSeparator7)))
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(age))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(272, 272, 272)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(depa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(charg, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ron, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(m1)
                    .addComponent(f1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(ag11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(depa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depa1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(adv, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adv1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(charg1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(charg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 47, 65));
        jLabel2.setText("Booking");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Logo Small.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mountain1.jpg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 47, 65));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Beautiful Sceneries....");

        l12.setEditable(false);
        l12.setBackground(new java.awt.Color(97, 212, 195));
        l12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        l12.setForeground(new java.awt.Color(36, 47, 65));
        l12.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        l12.setBorder(null);

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log Out");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jMenuBar1.setBackground(new java.awt.Color(97, 212, 195));
        jMenuBar1.setBorder(null);

        viewm.setBackground(new java.awt.Color(97, 212, 195));
        viewm.setBorder(null);
        viewm.setForeground(new java.awt.Color(36, 47, 65));
        viewm.setText("View");
        viewm.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                viewmMouseMoved(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(97, 212, 195));
        Logout.setText("Log Out");
        Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutMouseMoved(evt);
            }
        });
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        viewm.add(Logout);

        MainMenu.setBackground(new java.awt.Color(97, 212, 195));
        MainMenu.setText("Main Menu");
        MainMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MainMenuMouseMoved(evt);
            }
        });
        MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuMouseClicked(evt);
            }
        });
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        viewm.add(MainMenu);

        exit.setBackground(new java.awt.Color(97, 212, 195));
        exit.setText("Exit");
        exit.setBorder(null);
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitMouseMoved(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        viewm.add(exit);

        jMenuBar1.add(viewm);

        backm.setForeground(new java.awt.Color(36, 47, 65));
        backm.setText("Back");
        backm.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmMouseClicked(evt);
            }
        });
        backm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backmMouseMoved(evt);
            }
        });
        jMenuBar1.add(backm);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1017, 713));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmMouseClicked
MainPage ob=new MainPage(l12.getText(),"");
ob.setVisible(true);
this.setVisible(false);
}//GEN-LAST:event_backmMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked

}//GEN-LAST:event_LogoutMouseClicked

    private void MainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuMouseClicked

}//GEN-LAST:event_MainMenuMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked

}//GEN-LAST:event_exitMouseClicked

    private void LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseMoved
Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
Logout.setCursor(cur1);
}//GEN-LAST:event_LogoutMouseMoved

    private void MainMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuMouseMoved
  Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
MainMenu.setCursor(cur1);
    }//GEN-LAST:event_MainMenuMouseMoved

    private void exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMoved
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
exit.setCursor(cur1);
    }//GEN-LAST:event_exitMouseMoved

    private void backmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmMouseMoved
Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
backm.setCursor(cur1);
    }//GEN-LAST:event_backmMouseMoved

    private void viewmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewmMouseMoved
Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
viewm.setCursor(cur1);
    }//GEN-LAST:event_viewmMouseMoved

    private void l1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseMoved
 Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
l1.setCursor(cur1);
}//GEN-LAST:event_l1MouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        try
    {
    Class.forName("java.sql.Driver");
    Connection con= DriverManager.getConnection("jdbc:mysql://localhost/Hotel","root","");
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("Select * from hotelbooking;");
    while(rs.next())
    {
        int n =rs.getInt(1);
        rn.setText(n+1+"");
    }
    con.close();
    st.close();
    rs.close();
}
    catch(Exception ob)
    { System.out.println(ob);}
   
    }//GEN-LAST:event_jPanel1MouseMoved

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
int nr=Integer.parseInt(rn.getText());
int room=Integer.parseInt(ron.getText());
String sname=name.getText();
String sadd=add.getText();
if(m1.isSelected())
{
    se="Male";
}
if(f1.isSelected())
{
    se="Female";
}
String arrival=ayear+"/"+amonth+"/"+adate;
String departure=dyear+"/"+dmonth+"/"+ddate;
int advance=Integer.parseInt(adv1.getText());
int charge=Integer.parseInt(charg1.getText());
int sage=Integer.parseInt(ag11.getText());
try
     {
      Class.forName("java.sql.Driver");
      Connection con= DriverManager.getConnection("jdbc:mysql://localhost/Hotel","root","");
      Statement st=con.createStatement();
      String nx="Insert into hotelbooking values("+nr+", "+room+", \""+sname+"\", \""+sadd+"\", \""+se+"\", "+sage+", \""+arrival+"\", \""+departure+"\", "+advance+", "+charge+");";
      st.executeUpdate(nx);
      con.close();
      st.close();
      JOptionPane.showMessageDialog(null,"Successful.");
     }
      catch(Exception ob)
      { JOptionPane.showMessageDialog(null,"Fill All the fields and checkboxes.");
        System.out.println(ob);
      }
    }//GEN-LAST:event_l1MouseClicked

    private void arrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrKeyTyped
String arrival=arr.getText();
int n=arrival.length();
if(n==2)
{
    arr.setText(arrival+"/");
    adate=arrival;
}
if(n==5)
{
     arr.setText(arrival+"/");
     amonth=arrival.substring(3,5);
}

    }//GEN-LAST:event_arrKeyTyped

    private void arrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrKeyPressed

    private void depaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depaKeyPressed

    }//GEN-LAST:event_depaKeyPressed

    private void depaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depaKeyTyped

    }//GEN-LAST:event_depaKeyTyped

    private void advKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_advKeyPressed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_ageKeyPressed

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_ageKeyTyped

    private void ag11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ag11KeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_ag11KeyPressed

    private void ag11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ag11KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_ag11KeyTyped

    private void depa1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depa1KeyPressed

}//GEN-LAST:event_depa1KeyPressed

    private void depa1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depa1KeyTyped
String departure=depa1.getText();
int n=departure.length();
if(n==2)
{
    depa1.setText(departure+"/");
    ddate=departure;
}
if(n==5)
{
     depa1.setText(departure+"/");
     dmonth=departure.substring(3,5);
}
     
}//GEN-LAST:event_depa1KeyTyped

    private void adv1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adv1KeyPressed

}//GEN-LAST:event_adv1KeyPressed

    private void adv1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adv1KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_adv1KeyTyped

    private void charg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_charg1KeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_charg1KeyPressed

    private void charg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_charg1KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_charg1KeyTyped

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
arr.setText("");
depa1.setText("");
adv1.setText("");
ag11.setText("");
charg1.setText("");
add.setText("");
name.setText("");
ron.setText("");
buttonGroup1.clearSelection();
        try
    {
    Class.forName("java.sql.Driver");
    Connection con= DriverManager.getConnection("jdbc:mysql://localhost/Hotel","root","");
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("Select * from hotelbooking;");
    while(rs.next())
    {
        int n =rs.getInt(1);
        rn.setText(n+1+"");
    }
    con.close();
    st.close();
    rs.close();
}
    catch(Exception ob)
    { System.out.println(ob);}

    }//GEN-LAST:event_l3MouseClicked

    private void l3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseMoved
    Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
l3.setCursor(cur1);     // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseMoved

    private void arrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arrFocusLost
String arrival=arr.getText();
int n=arrival.length();
if(n==10)
{
   ayear=arrival.substring(6,10);
}
    }//GEN-LAST:event_arrFocusLost

    private void depa1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_depa1FocusLost
String departure=depa1.getText();
int n=departure.length();
if(n==10)
{
   dyear=departure.substring(6,10);
}
    }//GEN-LAST:event_depa1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login ob=new Login();
        ob.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
Login ob=new Login();
ob.setVisible(true);
this.setVisible(false);       
    }//GEN-LAST:event_LogoutActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
   MainPage ob=new MainPage();
ob.setVisible(true);
this.setVisible(false);       
    }//GEN-LAST:event_MainMenuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        
    }//GEN-LAST:event_exitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem MainMenu;
    private javax.swing.JTextField add;
    private javax.swing.JTextField adv;
    private javax.swing.JTextField adv1;
    private javax.swing.JTextField ag11;
    private javax.swing.JTextField age;
    private javax.swing.JTextField arr;
    private javax.swing.JMenu backm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField charg;
    private javax.swing.JTextField charg1;
    private javax.swing.JTextField depa;
    private javax.swing.JTextField depa1;
    private javax.swing.JMenuItem exit;
    private javax.swing.JRadioButton f1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField l12;
    private javax.swing.JLabel l3;
    private javax.swing.JRadioButton m1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rn;
    private javax.swing.JTextField ron;
    private javax.swing.JMenu viewm;
    // End of variables declaration//GEN-END:variables

}
