
import java.awt.Cursor;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 22 Oct, 2018, 2:10:17 PM
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {
int s=0;String lname="",lid="";
    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quote = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        enterid1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        signuplabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        passwordlogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ");
        setBounds(new java.awt.Rectangle(300, 300, 500, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-40, 10, 430, 330);

        quote.setBackground(new java.awt.Color(255, 255, 255));
        quote.setFont(new java.awt.Font("Calibri", 1, 12));
        quote.setForeground(new java.awt.Color(36, 47, 65));
        quote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quote.setText("Sometimes life is going to hit you in the head with a brick. Don't lose faith.");
        jPanel1.add(quote);
        quote.setBounds(4, 500, 400, 16);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24));
        jLabel7.setForeground(new java.awt.Color(36, 47, 65));
        jLabel7.setText("HOME AWAY FROM HOME!!!");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 350, 310, 50);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(70, 390, 300, 40);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 70, 120, 44);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(40, 112, 90, 10);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 300, 150, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTER ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 160, 150, 23);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(40, 250, 320, 40);

        enterid1.setBackground(new java.awt.Color(36, 47, 65));
        enterid1.setFont(new java.awt.Font("Calibri", 1, 18));
        enterid1.setForeground(new java.awt.Color(255, 255, 255));
        enterid1.setText("Enter Id Here");
        enterid1.setBorder(null);
        enterid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterid1MouseClicked(evt);
            }
        });
        jPanel2.add(enterid1);
        enterid1.setBounds(40, 200, 320, 50);

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(40, 420, 110, 40);

        jPanel4.setBackground(new java.awt.Color(97, 212, 195));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cancel");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(250, 420, 110, 40);

        signuplabel.setFont(new java.awt.Font("Calibri", 1, 14));
        signuplabel.setForeground(new java.awt.Color(255, 255, 255));
        signuplabel.setText("Not a Member, Sign up.");
        signuplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplabelMouseClicked(evt);
            }
        });
        signuplabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                signuplabelMouseMoved(evt);
            }
        });
        jPanel2.add(signuplabel);
        signuplabel.setBounds(40, 490, 320, 17);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(40, 370, 320, 40);

        passwordlogin.setBackground(new java.awt.Color(36, 47, 65));
        passwordlogin.setFont(new java.awt.Font("Calibri", 1, 18));
        passwordlogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordlogin.setToolTipText("Enter Password Here");
        passwordlogin.setBorder(null);
        jPanel2.add(passwordlogin);
        passwordlogin.setBounds(40, 326, 320, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-812)/2, (screenSize.height-555)/2, 812, 555);
    }// </editor-fold>//GEN-END:initComponents

    private void enterid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterid1MouseClicked
enterid1.setText("");
    }//GEN-LAST:event_enterid1MouseClicked

    private void signuplabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelMouseMoved
Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
signuplabel.setCursor(cur1);
    }//GEN-LAST:event_signuplabelMouseMoved

    private void signuplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelMouseClicked
SignUp ob= new SignUp();
ob.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_signuplabelMouseClicked

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
jLabel5.setCursor(cur1);
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
jLabel6.setCursor(cur1);
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
lid=enterid1.getText();
String lpass=String.valueOf(passwordlogin.getPassword());
try
{
    Class.forName("java.sql.Driver");
    Connection con= DriverManager.getConnection("jdbc:mysql://localhost/Hotel","root","");
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("Select * from login;");
    while(rs.next())
    {
        String id=rs.getString(1);
        String pass=rs.getString(2);
        lname=rs.getString(3);
        if (id.equals(lid))
        {
            if(pass.equals(lpass))
            {
               s=s+1;

            }
        }
       
    }
    con.close();
    st.close();
    rs.close();
}
    catch(Exception ob)
    { System.out.println(ob);}
if(s==1)
{
    new MainPage("ID- "+lid,lname).setVisible(true);
               this.setVisible(false);
}
   else
        {
            JOptionPane.showMessageDialog(null,"Id or Password is Incorrect.");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterid1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField passwordlogin;
    private javax.swing.JLabel quote;
    private javax.swing.JLabel signuplabel;
    // End of variables declaration//GEN-END:variables

}
